version: '3'
services:
  ### Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5450:5432"  # Esto significa que el puerto 5451 en tu máquina local está conectado al puerto 5432 dentro del contenedor

  ### MySQL database for orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Esto significa que el puerto 3307 en tu máquina local está conectado al puerto 3307 dentro del contenedor

  ### Postgres database for Product
  db-product:
    container_name: db-product
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
    - "5433:5432"  # Esto significa que el puerto 5433 en tu máquina local está conectado al puerto 5432 dentro del contenedor

  ### Postgres database for Keyclock
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"  # Esto significa que el puerto 5434 en tu máquina local está conectado al puerto 5432 dentro del contenedor

      ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - "8081:8081"
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8081
